In [50]:
import pandas as pd
df = pd.read_csv('Breast_Cancer.csv')
delete_column = ['Status']
df.drop(columns=delete_column, inplace=True)
df.to_csv('Breast_Cancer.csv', index=False)
df.isnull().sum()

In [81]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df

,Age,Race,Marital Status,T Stage,N Stage,6th Stage,differentiate,Grade,A Stage,Tumor Size,Estrogen Status,Progesterone Status,Regional Node Examined,Reginol Node Positive,Survival Months
0,68,White,Married,T1,N1,IIA,Poorly differentiated,3,Regional,4,Positive,Positive,24,1,60
1,50,White,Married,T2,N2,IIIA,Moderately differentiated,2,Regional,35,Positive,Positive,14,5,62
2,58,White,Divorced,T3,N3,IIIC,Moderately differentiated,2,Regional,63,Positive,Positive,14,7,75
3,58,White,Married,T1,N1,IIA,Poorly differentiated,3,Regional,18,Positive,Positive,2,1,84
4,47,White,Married,T2,N1,IIB,Poorly differentiated,3,Regional,41,Positive,Positive,3,1,50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4019,62,Other,Married,T1,N1,IIA,Moderately differentiated,2,Regional,9,Positive,Positive,1,1,49
4020,56,White,Divorced,T2,N2,IIIA,Moderately differentiated,2,Regional,46,Positive,Positive,14,8,69
4021,68,White,Married,T2,N1,IIB,Moderately differentiated,2,Regional,22,Positive,Negative,11,3,69
4022,58,Black,Divorced,T2,N1,IIB,Moderately differentiated,2,Regional,44,Positive,Positive,11,1,72
4023,46,White,Married,T2,N1,IIB,Moderately differentiated,2,Regional,30,Positive,Positive,7,2,100

In [103]:
dfle = df
dfle['Race'] = le.fit_transform(dfle['Race'])
dfle['Marital Status'] = le.fit_transform(dfle['Marital Status'])
dfle['T Stage '] = le.fit_transform(dfle['T Stage '])
dfle['N Stage'] = le.fit_transform(dfle['N Stage'])
dfle['6th Stage'] = le.fit_transform(dfle['6th Stage'])
dfle['differentiate'] = le.fit_transform(dfle['differentiate'])
dfle['Grade'] = le.fit_transform(dfle['Grade'])
dfle['A Stage'] = le.fit_transform(dfle['A Stage'])
dfle['Tumor Size'] = le.fit_transform(dfle['Tumor Size'])
dfle['Estrogen Status'] = le.fit_transform(dfle['Estrogen Status'])
dfle['Progesterone Status'] = le.fit_transform(dfle['Progesterone Status'])

In [121]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
model = LinearRegression()

In [123]:
X = dfle.drop(['Survival Months'],axis='columns')
y = dfle['Survival Months']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
model.fit(X_train, y_train)

LinearRegression()

In [130]:
predictions = model.predict(X_test)
mae = mean_absolute_error(y_test, predictions)
mse = mean_squared_error(y_test, predictions)
r2 = r2_score(y_test, predictions)
r2
dfle

,Age,Race,Marital Status,T Stage,N Stage,6th Stage,differentiate,Grade,A Stage,Tumor Size,Estrogen Status,Progesterone Status,Regional Node Examined,Reginol Node Positive,Survival Months
0,68,2,1,0,0,0,1,3,1,1,1,1,24,1,60
1,50,2,1,1,1,2,0,2,1,1,1,1,14,5,62
2,58,2,0,2,2,4,0,2,1,1,1,1,14,7,75
3,58,2,1,0,0,0,1,3,1,1,1,1,2,1,84
4,47,2,1,1,0,1,1,3,1,1,1,1,3,1,50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4019,62,1,1,0,0,0,0,2,1,1,1,1,1,1,49
4020,56,2,0,1,1,2,0,2,1,1,1,1,14,8,69
4021,68,2,1,1,0,1,0,2,1,0,1,0,11,3,69
4022,58,0,0,1,0,1,0,2,1,1,1,1,11,1,72
4023,46,2,1,1,0,1,0,2,1,1,1,1,7,2,100

In [133]:
model.predict([[68, 2, 1, 0, 0, 0, 1, 3, 1, 1, 1, 1, 24, 1]])

C:\Users\JJ\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([75.21433188])

In [134]:
import matplotlib.pyplot as plt
plt.figure(figsize=(8, 6))
plt.scatter(y_test, predictions, color='blue', alpha=0.5)
plt.title('Actual vs Predicted')
plt.xlabel('Actual Values')
plt.ylabel('Predicted Values')
plt.grid(True)
plt.show()

NameError: name 'lt' is not defined