In [2]:
import pandas as pd
data = pd.read_csv(r"C:\Users\jeanl\College\Blocks\Block 3\Epic\Block3Epic\data_copy.csv")
data.head()
# Print the column names in the DataFrame
print(data.columns)

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\jeanl\\College\\Blocks\\Block 3\\Epic\\Block3Epic\\data_copy.csv'

In [ ]:
#T stage mapping
T_stage_mapping = {
    'T1': 1,
    'T2': 2,
    'T3': 3,
    'T4': 4
}

# Map the text values to numeric codes
data['T Stage'] = data['T Stage'].map(T_stage_mapping)
data.head()

,Age,Race,Marital Status,T Stage,N Stage,6th Stage,differentiate,Grade,A Stage,Tumor Size,Estrogen Status,Progesterone Status,Regional Node Examined,Reginol Node Positive,Survival Months,Status
0,68,White,Married,1,N1,IIA,Poorly differentiated,3,Regional,4,Positive,Positive,24,1,60,Alive
1,50,White,Married,2,N2,IIIA,Moderately differentiated,2,Regional,35,Positive,Positive,14,5,62,Alive
2,58,White,Divorced,3,N3,IIIC,Moderately differentiated,2,Regional,63,Positive,Positive,14,7,75,Alive
3,58,White,Married,1,N1,IIA,Poorly differentiated,3,Regional,18,Positive,Positive,2,1,84,Alive
4,47,White,Married,2,N1,IIB,Poorly differentiated,3,Regional,41,Positive,Positive,3,1,50,Alive

In [ ]:
#N stage mapping
N_stage_mapping = {
    'N1': 1,
    'N2': 2,
    'N3': 3,
    'N4': 4
}

# Map the text values to numeric codes
data['N Stage'] = data['N Stage'].map(N_stage_mapping)
data.head()

,Age,Race,Marital Status,T Stage,N Stage,6th Stage,differentiate,Grade,A Stage,Tumor Size,Estrogen Status,Progesterone Status,Regional Node Examined,Reginol Node Positive,Survival Months,Status
0,68,White,Married,1,1,IIA,Poorly differentiated,3,Regional,4,Positive,Positive,24,1,60,Alive
1,50,White,Married,2,2,IIIA,Moderately differentiated,2,Regional,35,Positive,Positive,14,5,62,Alive
2,58,White,Divorced,3,3,IIIC,Moderately differentiated,2,Regional,63,Positive,Positive,14,7,75,Alive
3,58,White,Married,1,1,IIA,Poorly differentiated,3,Regional,18,Positive,Positive,2,1,84,Alive
4,47,White,Married,2,1,IIB,Poorly differentiated,3,Regional,41,Positive,Positive,3,1,50,Alive

In [ ]:
#6th stage mapping
sixth_stage_mapping = {
    'IA': 1,
    'IB': 2,
    'IC': 3,
    'IIA': 4,
    'IIB': 5,
    'IIC': 6,
    'IIIA': 7,
    'IIIB': 8,
    'IIIC': 9,
    'IV': 10,
}

# Map the text values to numeric codes
data['6th Stage'] = data['6th Stage'].map(sixth_stage_mapping)
data.head()

,Age,Race,Marital Status,T Stage,N Stage,6th Stage,differentiate,Grade,A Stage,Tumor Size,Estrogen Status,Progesterone Status,Regional Node Examined,Reginol Node Positive,Survival Months,Status
0,68,White,Married,1,1,4,1,3,Regional,4,Positive,Positive,24,1,60,Alive
1,50,White,Married,2,2,7,2,2,Regional,35,Positive,Positive,14,5,62,Alive
2,58,White,Divorced,3,3,9,2,2,Regional,63,Positive,Positive,14,7,75,Alive
3,58,White,Married,1,1,4,1,3,Regional,18,Positive,Positive,2,1,84,Alive
4,47,White,Married,2,1,5,1,3,Regional,41,Positive,Positive,3,1,50,Alive

In [ ]:
#Differenciate mapping
#Because for most other values eg T, N stage, grade etc, bigger numbers correspond to worst cancer, I have made the choice to map poorer differenciation to a higher value.

differenciate_mapping = {
    'Undifferentiated': 0,
    'Poorly differentiated': 1,
    'Moderately differentiated': 2,
    'Well differentiated': 3
}
# Map the text values to numeric codes
data['differentiate'] = data['differentiate'].map(differenciate_mapping)
data.head()

,Age,Race,Marital Status,T Stage,N Stage,6th Stage,differentiate,Grade,A Stage,Tumor Size,Estrogen Status,Progesterone Status,Regional Node Examined,Reginol Node Positive,Survival Months,Status
0,68,White,Married,1,1,IIA,1,3,Regional,4,Positive,Positive,24,1,60,Alive
1,50,White,Married,2,2,IIIA,2,2,Regional,35,Positive,Positive,14,5,62,Alive
2,58,White,Divorced,3,3,IIIC,2,2,Regional,63,Positive,Positive,14,7,75,Alive
3,58,White,Married,1,1,IIA,1,3,Regional,18,Positive,Positive,2,1,84,Alive
4,47,White,Married,2,1,IIB,1,3,Regional,41,Positive,Positive,3,1,50,Alive

In [ ]:
#A stage mapping
A_Stage_mapping = {
    'Regional': 0,
    'Distant': 1,
}
# Map the text values to numeric codes
data['A Stage'] = data['A Stage'].map(A_Stage_mapping)
data.head()

,Age,Race,Marital Status,T Stage,N Stage,6th Stage,differentiate,Grade,A Stage,Tumor Size,Estrogen Status,Progesterone Status,Regional Node Examined,Reginol Node Positive,Survival Months,Status
0,68,White,Married,1,1,4,1,3,0,4,Positive,Positive,24,1,60,Alive
1,50,White,Married,2,2,7,2,2,0,35,Positive,Positive,14,5,62,Alive
2,58,White,Divorced,3,3,9,2,2,0,63,Positive,Positive,14,7,75,Alive
3,58,White,Married,1,1,4,1,3,0,18,Positive,Positive,2,1,84,Alive
4,47,White,Married,2,1,5,1,3,0,41,Positive,Positive,3,1,50,Alive

In [ ]:
#Estrogen status mapping
estrogen_mapping = {
    'Negative': 0,
    'Positive': 1,
}
# Map the text values to numeric codes
data['Estrogen Status'] = data['Estrogen Status'].map(estrogen_mapping)
data.head()

,Age,Race,Marital Status,T Stage,N Stage,6th Stage,differentiate,Grade,A Stage,Tumor Size,Estrogen Status,Progesterone Status,Regional Node Examined,Reginol Node Positive,Survival Months,Status
0,68,White,Married,1,1,4,1,3,0,4,1,Positive,24,1,60,Alive
1,50,White,Married,2,2,7,2,2,0,35,1,Positive,14,5,62,Alive
2,58,White,Divorced,3,3,9,2,2,0,63,1,Positive,14,7,75,Alive
3,58,White,Married,1,1,4,1,3,0,18,1,Positive,2,1,84,Alive
4,47,White,Married,2,1,5,1,3,0,41,1,Positive,3,1,50,Alive

In [ ]:
#Progesterone status mapping
Progesterone_mapping = {
    'Negative': 0,
    'Positive': 1,
}
# Map the text values to numeric codes
data['Progesterone Status'] = data['Progesterone Status'].map(Progesterone_mapping)
data.head()

,Age,Race,Marital Status,T Stage,N Stage,6th Stage,differentiate,Grade,A Stage,Tumor Size,Estrogen Status,Progesterone Status,Regional Node Examined,Reginol Node Positive,Survival Months,Status
0,68,White,Married,1,1,4,1,3,0,4,1,1,24,1,60,Alive
1,50,White,Married,2,2,7,2,2,0,35,1,1,14,5,62,Alive
2,58,White,Divorced,3,3,9,2,2,0,63,1,1,14,7,75,Alive
3,58,White,Married,1,1,4,1,3,0,18,1,1,2,1,84,Alive
4,47,White,Married,2,1,5,1,3,0,41,1,1,3,1,50,Alive

In [ ]:
#Survival mapping
survival_mapping = {
    'Dead': 0,
    'Alive': 1,
}
# Map the text values to numeric codes
data['Status'] = data['Status'].map(survival_mapping)
data.head()

,Age,Race,Marital Status,T Stage,N Stage,6th Stage,differentiate,Grade,A Stage,Tumor Size,Estrogen Status,Progesterone Status,Regional Node Examined,Reginol Node Positive,Survival Months,Status
0,68,White,Married,1,1,4,1,3,0,4,1,1,24,1,60,1
1,50,White,Married,2,2,7,2,2,0,35,1,1,14,5,62,1
2,58,White,Divorced,3,3,9,2,2,0,63,1,1,14,7,75,1
3,58,White,Married,1,1,4,1,3,0,18,1,1,2,1,84,1
4,47,White,Married,2,1,5,1,3,0,41,1,1,3,1,50,1